-- Migration: Add tool-specific usage tracking columns
-- Date: 2025-01-13
-- Description: Add columns to track image generations, video generations, and web searches per user per day/month

-- Add tool usage columns to user_daily_usage table
ALTER TABLE user_daily_usage 
ADD COLUMN IF NOT EXISTS image_generations_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_generations_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS web_searches_count INTEGER NOT NULL DEFAULT 0;

-- Add tool usage columns to user_monthly_usage table
ALTER TABLE user_monthly_usage 
ADD COLUMN IF NOT EXISTS image_generations_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_generations_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS web_searches_count INTEGER NOT NULL DEFAULT 0;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_user_daily_usage_tool_counts 
ON user_daily_usage (user_id, usage_date, image_generations_count, video_generations_count, web_searches_count);

CREATE INDEX IF NOT EXISTS idx_user_monthly_usage_tool_counts 
ON user_monthly_usage (user_id, usage_year, usage_month, image_generations_count, video_generations_count, web_searches_count);

-- Add comments to document the new columns
COMMENT ON COLUMN user_daily_usage.image_generations_count IS 'Number of images generated by user on this date';
COMMENT ON COLUMN user_daily_usage.video_generations_count IS 'Number of videos generated by user on this date';
COMMENT ON COLUMN user_daily_usage.web_searches_count IS 'Number of web searches performed by user on this date';

COMMENT ON COLUMN user_monthly_usage.image_generations_count IS 'Number of images generated by user in this month';
COMMENT ON COLUMN user_monthly_usage.video_generations_count IS 'Number of videos generated by user in this month';
COMMENT ON COLUMN user_monthly_usage.web_searches_count IS 'Number of web searches performed by user in this month';